### ISSUE TITLE
tensorrt是deb安装的么？谢谢

### ISSUE THREAD

**Issue by hyaihjq** [Syencil/tensorRT#15]
tensorrt是deb安装的么？谢谢

**Comment by hyaihjq** [comment]
无论是docker还是本地安装，一直报/usr/bin/ld: cannot find -lhourglasstrt
/usr/bin/ld: cannot find -llibnvinfer.so.7.0.0
/usr/bin/ld: cannot find -llibnvonnxparser.so.7.0.0
错误，无语

**Comment by hyaihjq** [comment]
麻烦您回复下，tensorrt7.0，cuda10.2，cudnn7.6.5

**Comment by Syencil** [comment]
libhourglasstrt.so 那个是要先make libhourglasstrt 另外两个你检查下你有没有这个文件

**Comment by hyaihjq** [comment]
我设置set(TRT_LIB /usr/lib/x86_64-linux-gnu/libnvinfer.so.7.0.0 /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.7.0.0 /usr/lib/x86_64-linux-gnu/libcuda.so)已经没有/usr/bin/ld: cannot find -llibnvinfer.so.7.0.0
/usr/bin/ld: cannot find -llibnvonnxparser.so.7.0.0错误
但是make时候依然
/usr/bin/ld: cannot find -lhourglasstrt
collect2: error: ld returned 1 exit status
CMakeFiles/hourglass.dir/build.make:145: recipe for target 'bin/hourglass' failed
make[2]: *** [bin/hourglass] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/hourglass.dir/all' failed
make[1]: *** [CMakeFiles/hourglass.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Syencil** [comment]
你应该是去设置lib库的dir 而不是直接set 具体的可以看看cmake的语法 hourglasstrt那个问题是你首先需要编译生成这个lib 才能去链接 make + 需要编译的名字 这点我没写清楚 之后会再更新一版readme

**Comment by hyaihjq** [comment]
ok，已经解决了，除了 hourglasstrt和resnettrt

**Comment by hyaihjq** [comment]
谢谢

**Comment by ElegantLin** [comment]
平台：Jetson Nano
TRT lib在`/usr/lib/aarch64-linux-gnu/libnvinfer.so.7`和`/usr/lib/aarch64-linux-gnu/libnvonnxparser.so.7`

操作的步骤是

```
cmake -DCMAKE_BUILD_TYPE=Release ..
make retinanettrt
make retinanet
```

```
/usr/bin/ld: cannot find -llibnvinfer.so.7.0.0
/usr/bin/ld: cannot find -llibnvonnxparser.so.7.0.0
collect2: error: ld returned 1 exit status
CMakeFiles/retinanet.dir/build.make:113: recipe for target 'bin/retinanet' failed
make[3]: *** [bin/retinanet] Error 1
CMakeFiles/Makefile2:511: recipe for target 'CMakeFiles/retinanet.dir/all' failed
make[2]: *** [CMakeFiles/retinanet.dir/all] Error 2
CMakeFiles/Makefile2:523: recipe for target 'CMakeFiles/retinanet.dir/rule' failed
make[1]: *** [CMakeFiles/retinanet.dir/rule] Error 2
Makefile:274: recipe for target 'retinanet' failed
make: *** [retinanet] Error 2
```

请问应该怎么解决呢？

谢谢！

已经解决。
